NDLANO/article-import

src/main/scala/no/ndla/articleimport/ComponentRegistry.scala
src/main/scala/no/ndla/articleimport/service/converters/RelatedContentConverter.scala
src/main/scala/no/ndla/articleimport/service/converters/contentbrowser/VideoConverterModule.scala

Samme endringer som i [denne](https://github.com/NDLANO/article-api/pull/196)

fix relatedcontentconverter bugs #811

---

build.sbt
src/main/scala/no/ndla/articleimport/controller/InternController.scala
src/main/scala/no/ndla/articleimport/service/ExtractService.scala
src/main/scala/no/ndla/articleimport/service/converters/HTMLCleaner.scala
src/main/scala/no/ndla/articleimport/service/converters/HtmlTagGenerator.scala
src/main/scala/no/ndla/articleimport/service/converters/VisualElementConverter.scala
src/main/scala/no/ndla/articleimport/service/converters/contentbrowser/AudioConverterModule.scala
src/test/scala/no/ndla/articleimport/service/converters/VisualElementConverterTest.scala
src/test/scala/no/ndla/articleimport/service/converters/contentbrowser/AudioConverterTest.scala
src/test/scala/no/ndla/articleimport/service/converters/contentbrowser/ImageConverterTest.scala
src/test/scala/no/ndla/articleimport/service/converters/contentbrowser/LenkeConverterTest.scala

* Includes `commons-lang % commons-lang` from apache for `escapeHtml`
* Upgrades `jsoup` to 1.11.2

#888: Imports audio embeds with captions

---

build.sbt
src/main/scala/no/ndla/articleimport/model/domain/ExternalEmbedMetaWithTitle.scala
src/main/scala/no/ndla/articleimport/service/converters/HtmlTagGenerator.scala
src/main/scala/no/ndla/articleimport/service/converters/RelatedContentConverter.scala
src/test/scala/no/ndla/articleimport/service/converters/RelatedContentConverterTest.scala

Fails because of validation: https://github.com/NDLANO/validation/pull/17
Needs sync with frontend

#1042: Adds support for related link nodes

---

src/main/scala/no/ndla/articleimport/service/converters/contentbrowser/ContentBrowser.scala
src/test/scala/no/ndla/articleimport/service/converters/contentbrowser/ContentBrowserStringTest.scala

#1065: Escapes parenthesis when extracting creating DOMPath for contentBrowser

---

src/main/scala/no/ndla/articleimport/service/converters/contentbrowser/GeneralContentConverterModule.scala

resolves https://github.com/NDLANO/Issues/issues/1077

#1077: Use nodeType instead of contentType when inserting text

---

src/main/scala/no/ndla/articleimport/ComponentRegistry.scala
src/main/scala/no/ndla/articleimport/integration/ConverterModule.scala
src/main/scala/no/ndla/articleimport/model/api/NDLAErrors.scala
src/main/scala/no/ndla/articleimport/model/domain/ImportStatus.scala
src/main/scala/no/ndla/articleimport/service/ExtractConvertStoreContent.scala
src/main/scala/no/ndla/articleimport/service/converters/LeafNodeConverter.scala
src/main/scala/no/ndla/articleimport/service/converters/RelatedContentConverter.scala
src/main/scala/no/ndla/articleimport/service/converters/SimpleTagConverter.scala
src/main/scala/no/ndla/articleimport/service/converters/VisualElementConverter.scala
src/main/scala/no/ndla/articleimport/service/converters/contentbrowser/ContentBrowserConverter.scala
src/main/scala/no/ndla/articleimport/service/converters/contentbrowser/LenkeConverterModule.scala
src/test/scala/no/ndla/articleimport/TestEnvironment.scala
src/test/scala/no/ndla/articleimport/service/ConverterServiceTest.scala
src/test/scala/no/ndla/articleimport/service/ExtractConvertStoreContentTest.scala
src/test/scala/no/ndla/articleimport/service/converters/LeafNodeConverterTest.scala
src/test/scala/no/ndla/articleimport/service/converters/RelatedContentConverterTest.scala
src/test/scala/no/ndla/articleimport/service/converters/SimpleTagConverterTest.scala
src/test/scala/no/ndla/articleimport/service/converters/VisualElementConverterTest.scala
src/test/scala/no/ndla/articleimport/service/converters/contentbrowser/ContentBrowserConverterTest.scala
src/test/scala/no/ndla/articleimport/service/converters/contentbrowser/GeneralContentConverterModuleTest.scala
src/test/scala/no/ndla/articleimport/service/converters/contentbrowser/LenkeConverterModuleTest.scala

resolves https://github.com/NDLANO/Issues/issues/1079
Sorry for the big ¯\_ツ_/¯

#1079: Some errors, like failed related and failed contentbrowser are now imported

---

src/main/scala/no/ndla/articleimport/integration/DraftApiClient.scala

resolves https://github.com/NDLANO/Issues/issues/1086

send created and updated time as query params to draft-api #1086

---

build.sbt
src/main/scala/no/ndla/articleimport/service/converters/LeafNodeConverter.scala
src/main/scala/no/ndla/articleimport/service/converters/SimpleTagConverter.scala
src/main/scala/no/ndla/articleimport/service/converters/contentbrowser/LenkeConverterModule.scala
src/test/scala/no/ndla/articleimport/service/converters/SimpleTagConverterTest.scala
src/test/scala/no/ndla/articleimport/service/converters/contentbrowser/LenkeConverterModuleTest.scala

connects to https://github.com/NDLANO/Issues/issues/1096
Waiting for: https://github.com/NDLANO/validation/pull/20
- Fixes vimeopro
- Removes commoncraft
- Adds livestream.com
- Adds channel9.msdn.com
- Converts http iframe embeds to https

#1096: Fixes vimeopro, Adds livestream and channel9.msdn.com.

---

build.sbt
src/main/scala/no/ndla/articleimport/service/converters/contentbrowser/LenkeConverterModule.scala

connects to https://github.com/NDLANO/Issues/issues/1096
Waiting for: https://github.com/NDLANO/validation/pull/22

#1096: Adds tomknudsen as valid iframe embed

---

src/main/scala/no/ndla/articleimport/integration/DraftApiClient.scala
src/main/scala/no/ndla/articleimport/service/ExtractService.scala

resolves https://github.com/NDLANO/Issues/issues/1108

#1108: Don't return error first time concept is imported.

---

build.sbt
src/main/scala/no/ndla/articleimport/model/domain/UploadedFile.scala
src/main/scala/no/ndla/articleimport/service/ConverterService.scala
src/main/scala/no/ndla/articleimport/service/converters/FileDivConverter.scala
src/main/scala/no/ndla/articleimport/service/converters/HtmlTagGenerator.scala
src/main/scala/no/ndla/articleimport/service/converters/contentbrowser/FilConverterModule.scala
src/test/scala/no/ndla/articleimport/service/ConverterServiceTest.scala
src/test/scala/no/ndla/articleimport/service/converters/contentbrowser/FilConverterModuleModuleTest.scala

connects to https://github.com/NDLANO/issues/issues/1058

#1058: Implements importing file embeds with path rather than full url

---

src/main/scala/no/ndla/articleimport/integration/DraftApiClient.scala
src/main/scala/no/ndla/articleimport/service/ExtractConvertStoreContent.scala
src/test/scala/no/ndla/articleimport/service/ExtractConvertStoreContentTest.scala

connects to https://github.com/NDLANO/Issues/issues/1146

#1146: Store all nodeIds when importing article

---

src/main/scala/no/ndla/articleimport/service/converters/RelatedContentConverter.scala
src/test/scala/no/ndla/articleimport/service/converters/RelatedContentConverterTest.scala

#1157: Lookups of related nodes in taxonomy is now done using main nid

---

src/main/scala/no/ndla/articleimport/model/domain/Language.scala
src/test/scala/no/ndla/articleimport/model/domain/LanguageTest.scala

resolves https://github.com/NDLANO/Issues/issues/1199

#1199: fixes findByLanguageOrBestEffort to use correct language variable

---

src/main/scala/no/ndla/articleimport/controller/InternController.scala
src/main/scala/no/ndla/articleimport/integration/DraftApiClient.scala
src/main/scala/no/ndla/articleimport/model/domain/ImportStatus.scala
src/main/scala/no/ndla/articleimport/model/domain/package.scala
src/main/scala/no/ndla/articleimport/service/ExtractConvertStoreContent.scala
src/test/scala/no/ndla/articleimport/controller/InternControllerTest.scala
src/test/scala/no/ndla/articleimport/service/ExtractConvertStoreContentTest.scala

connects to NDLANO/Issues#1243
depens on https://github.com/NDLANO/draft-api/pull/67
Checks whether the given importId is the same as the one stored in draft-api and if they are equal, skip import for current article.

#1243: Check ImportId before importing

---

build.sbt

connects to NDLANO/Issues#1300

#1300: Bump validation to remove h5/h6

---

src/main/scala/no/ndla/articleimport/service/converters/contentbrowser/GeneralContentConverterModule.scala
src/test/scala/no/ndla/articleimport/service/converters/contentbrowser/GeneralContentConverterModuleTest.scala

connects to https://github.com/NDLANO/Issues/issues/1305

#1305: Makes only inline and collapsed_body combine licenses and authors

---

src/main/scala/no/ndla/articleimport/service/converters/SimpleTagConverter.scala
src/test/scala/no/ndla/articleimport/service/converters/SimpleTagConverterTest.scala

resolves https://github.com/NDLANO/Issues/issues/1301

#1301: Chinese text should get lang tags with zh rather than font-size

---

src/main/scala/no/ndla/articleimport/service/converters/HTMLCleaner.scala
src/test/scala/no/ndla/articleimport/service/converters/HTMLCleanerTest.scala

#909: h2's in asides should be converted to h1's

---

src/main/scala/no/ndla/articleimport/service/converters/contentbrowser/VideoConverterModule.scala
src/test/scala/no/ndla/articleimport/service/converters/contentbrowser/VideoConverterModuleTest.scala

resolves https://github.com/NDLANO/Issues/issues/1372

#1327: Makes lightbox videos inserted as anchor tags

---

src/main/scala/no/ndla/articleimport/service/converters/LeafNodeConverter.scala
src/test/scala/no/ndla/articleimport/service/converters/LeafNodeConverterTest.scala

Fixes NDLANO/issues#1384
* Uses metadescription from imported node

Use metaDescription from node

---

src/main/scala/no/ndla/articleimport/service/converters/contentbrowser/LenkeConverterModule.scala
src/test/scala/no/ndla/articleimport/service/converters/contentbrowser/LenkeConverterModuleTest.scala

Fixes import of youtube embeds (ugly code, but works)

Support youtube embeds on different format.

---

src/main/scala/no/ndla/articleimport/ArticleImportProperties.scala
src/main/scala/no/ndla/articleimport/integration/MigrationApiClient.scala
src/main/scala/no/ndla/articleimport/model/domain/ConverterModels.scala
src/main/scala/no/ndla/articleimport/service/AttachmentStorageService.scala
src/test/scala/no/ndla/articleimport/UnitSuite.scala
src/test/scala/no/ndla/articleimport/service/ConverterServiceTest.scala

connects to NDLANO/Issues#1394

#1394: Fetches files from red with basic auth rather than ndla.no

---

src/main/scala/no/ndla/articleimport/service/converters/SimpleTagConverter.scala
src/test/scala/no/ndla/articleimport/service/converters/SimpleTagConverterTest.scala

resolves https://github.com/NDLANO/Issues/issues/1398

#1398: Wraps all chinese text in spans with lang=zh attribute

---

build.sbt
src/main/scala/no/ndla/articleimport/service/converters/contentbrowser/LenkeConverterModule.scala
src/test/scala/no/ndla/articleimport/service/converters/contentbrowser/LenkeConverterModuleTest.scala

Support for several new embeds.

Bumped validation. Extra embeds.

---

src/main/scala/no/ndla/articleimport/service/converters/contentbrowser/GeneralContentConverterModule.scala
src/main/scala/no/ndla/articleimport/service/converters/contentbrowser/H5PConverterModule.scala
src/main/scala/no/ndla/articleimport/service/converters/contentbrowser/LenkeConverterModule.scala
src/main/scala/no/ndla/articleimport/service/converters/contentbrowser/VideoConverterModule.scala
src/main/scala/no/ndla/articleimport/service/converters/package.scala
src/test/scala/no/ndla/articleimport/service/converters/contentbrowser/H5PConverterModuleTest.scala

#1417: Inserts H5P as link if insertion is link or lightbox

---

src/main/scala/no/ndla/articleimport/service/converters/TableConverter.scala
src/test/scala/no/ndla/articleimport/service/converters/TableConverterTest.scala

handle tables with header-cells in column #1424

---

src/main/scala/no/ndla/articleimport/service/converters/RelatedContentConverter.scala

Fixes NDLANO/issues#1426
* Sjekker at minst en node er tilgjengelig. Enten nid eller mainNid

Check at least one nid in taxonomy

---

src/main/scala/no/ndla/articleimport/integration/MigrationApiClient.scala
src/test/scala/no/ndla/articleimport/integration/MigrationApiClientTest.scala

Do not import visualelement for all articles

---

build.sbt
src/main/scala/no/ndla/articleimport/service/converters/contentbrowser/LenkeConverterModule.scala

connects to NDLANO/Issues#1508

#1508: Adds concord and worldbank as iframe embeds

---

src/main/scala/no/ndla/articleimport/service/converters/contentbrowser/LenkeConverterModule.scala
src/test/scala/no/ndla/articleimport/service/converters/contentbrowser/LenkeConverterModuleTest.scala

resolves to NDLANO/Issues#1527

#1527: Handle youtube embeds with no embed code

---

src/main/scala/no/ndla/articleimport/service/converters/LeafNodeConverter.scala
src/main/scala/no/ndla/articleimport/service/converters/MetaInfoConverter.scala
src/test/scala/no/ndla/articleimport/service/converters/MetaInfoConverterTest.scala

connects to NDLANO/Issues#1530

#1530: Derives articleType from taxonomy when possible

---

src/main/scala/no/ndla/articleimport/ArticleImportProperties.scala
src/main/scala/no/ndla/articleimport/ComponentRegistry.scala

connects to NDLANO/Issues#1575

#1575: Use s3 correct name and detect s3 region automagically
